<?php echo $this->doctype(); ?>
<html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />        
            <?php echo $this->headTitle($this->translate('Quiz Show Rural Coopavel 2015'))->setSeparator(' - ')->setAutoEscape(false)?>
            <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0')?>

            <!-- Le styles -->
            <?php
												echo $this->headLink ( array (
														'rel' => 'shortcut icon',
														'type' => 'image/vnd.microsoft.icon',
														'href' => $this->basePath () . '/images/favicon.ico' 
												) )->prependStylesheet ( $this->basePath () . '/css/quizCoopavel.css' )?>

            <!-- Scripts -->
            <?php echo $this->headScript()->prependFile($this->basePath() . '/js/jquery-2.1.3.js')
                                          ->prependFile($this->basePath() . '/js/quizCoopavel.js');?>
    </head>
<body>

	<div class="container">
	<?php echo $this->content;?>
	<br>
	</div>
</body>
</html>
