<html>
<header>
	<title>Quiz</title>
	<link rel="stylesheet" type="text/css" href="css/quizCoopavel.css">
	<script type="text/javascript" src="js/jquery-2.1.3.js"></script>
	<script type="text/javascript" src="js/quizCoopavel.js"></script>
</header>
<body>
	<div id="cover"></div>

	<div id="page">
		<div class="conteudo">
			<div id="questao" class="questao"></div>
			<div class="alternativas">
				<div id="alternativaA" class="alternativa" style="width: 83.2%"></div>
				<div id="alternativaB" class="alternativa" style="width: 81.6%"></div>
				<div id="alternativaC" class="alternativa"></div>
			</div>
		</div>
	</div>
</body>
</html>